csea-nitc/Minerva

- minerva-frontend/src/app/components/history/History.jsx
The previous PR was a misunderstanding between me and the design team so I closed the previous PR and created a new one
I had to update the animation for the text again
Edited History component
minerva-frontend/src/app/components/history/History.jsx
> Rithvik - Animation Update

- minerva-frontend/src/app/components/footer/Footer.jsx
> fixed footer sizing

- minerva-frontend/src/app/announcements/page.js
- minerva-frontend/src/app/components/navbar/Navbar.js
- minerva-frontend/src/app/news/page.js
created an announements page and seperated news and announcements
> added announcements page

- minerva-frontend/src/app/about-site/page.js
- minerva-frontend/src/app/awards/page.js
- minerva-frontend/src/app/components/navbar/Navbar.js
- minerva-frontend/src/app/components/programmesutil/infosection.js
- minerva-frontend/src/app/programmes/page.js
Fixed the z index on those pages, and fixed routing for activities in navbar
PS: Please ignore the indentation changes my code formatter does that 😭
modified:   minerva-frontend/src/app/about-site/page.js
modified:   minerva-frontend/src/app/awards/page.js
modified:   minerva-frontend/src/app/components/programmesutil/infosection.js
modified:   minerva-frontend/src/app/programmes/page.js
modified:   minerva-frontend\src\app\components\navbar\Navbar.js
> Fixed Awards and Programmes, also some minor issues

- minerva-frontend/src/app/components/newscomp/ListComp.jsx
rendered PDF component for PDF links in ListComp
> rendered pdf comp for pdf link in ListComp

- minerva-frontend/package-lock.json
- minerva-frontend/src/app/news/page.js
Fixed the z-index for the news page :)
> Fixed News Page

- minerva-frontend/src/app/components/newscomp/ListComp.jsx
- minerva-frontend/src/app/components/sidebar/Sidebar.jsx
- minerva-frontend/src/app/news/page.js
- minerva-frontend/src/app/node/[slug]/page.js
- rendered quick links , rendered pages dynamically based on Title( slug ) 
- fixed link-highlights in mardown component
> quick links rendering

- minerva-frontend/src/app/components/graph/Graph.jsx
- minerva-frontend/src/app/placements/page.js
rendered graph component in placements page
> edited graph component in placement page

- minerva-frontend/src/app/components/navbar/Navbar.js
- minerva-frontend/src/app/internships/page.js
- added internship page 
- fixed route in navbar for placements and internship pages
> added internship page

- minerva-frontend/src/app/components/heropage/Hero.jsx
- minerva-frontend/src/app/components/herosupport/Herosupport.jsx
added the scrolling over img effect, fixed the text aligning and fixed responsiveness
> made the changes on homepage

- minerva-frontend/src/app/adhoc/page.js
- minerva-frontend/src/app/components/facultydetails/FacultyDetails.jsx
- minerva-frontend/src/app/components/navbar/Navbar.js
- minerva-frontend/src/app/placements/page.js
- minerva-frontend/src/app/staff/page.js
- created adhoc page 
- created staff page 
- small change to field name in faculty component 
- small change in placements page
> added adhoc and staff pages

- minerva-frontend/src/app/page.js
> added responsiveness to landing(refactored from main)

- minerva-frontend/src/app/components/facultydetails/FacultyDetails.jsx
- minerva-frontend/src/app/faculty/page.js
Changed the Card Component in the faculty page and grid layout changes
> changed card in facultypage

- minerva-frontend/src/app/announcements/[id]/page.js
- minerva-frontend/src/app/components/herosupport/Herosupport.jsx
- minerva-frontend/src/app/components/newscomp/ListComp.jsx
- minerva-frontend/src/app/components/sidebar/Sidebar.jsx
-  edited logic on side bar page render for quick links 
-  created dynamic pages for latest announcements in landing page
> dyanamic links on home page - latest announcemnets

- minerva-frontend/src/app/components/image-carousel/swiper.jsx
- minerva-frontend/src/app/components/lab_card/card.css
- minerva-frontend/src/app/components/lab_card/card.jsx
- minerva-frontend/src/app/labs/page.jsx
> Fixed Labs page

- minerva-frontend/src/app/components/image-carousel/swiper.jsx
- minerva-frontend/src/app/components/lab_card/card.css
- minerva-frontend/src/app/components/lab_card/card.jsx
- minerva-frontend/src/app/laboratories/page.jsx
> Revert "Fixed Labs page" (Breaks the swiper)

- minerva-frontend/src/app/components/footer/Footer.jsx
- minerva-frontend/src/app/components/pdf/PDF.js
1. updated footer font size 
2. made the list com,p responsive
> modified the list component and updated the font size

- minerva-frontend/src/app/components/sidebar/Sidebar.jsx
- minerva-frontend/src/app/credits/page.jsx
- minerva-frontend/src/app/downloads/page.js
- minerva-frontend/src/app/faculty/page.js
Fixed the following bugs
- Sidebar button not attached properly for landscape on mobile(and some tablet sizes too)
- Sidebar “Home” doesnt link to / route but just has href=#
- HOD card Homepage field rendering
- HOD card details text size is too small(isnt consistent with the test size in card details) in /faculty route
Also added the Downloads page /downloads
Misc Changes
- Include my full name “M Rithvik Reddy” instead of “Rithvik” in the credits page
- Change my name to Aditya  in the credits page
- Richies linkedin
> Bug fixed and Misc changes - Rithvik

- minerva-frontend/src/app/components/loading/loading.jsx
- minerva-frontend/src/app/contact/page.js
1. HOD detail links color is still blue instead of purple in /contact route: fixed colors
2. Loading component in hero page for quick links and brochure not centered for mobile view: commented a line in loading.js file, which was rendering a text.
> fixed bugs in loading and contact page

- minerva-frontend/src/app/components/footer/Footer.jsx
- minerva-frontend/src/app/components/heropage/Hero.jsx
- minerva-frontend/src/app/components/herosupport/Herosupport.jsx
- minerva-frontend/src/app/components/loading/loading.jsx
- minerva-frontend/src/app/components/sidebar/Sidebar.jsx
- minerva-frontend/src/app/csea/page.js
- Moved UG and PG brochures to side bar 
- Moved Quick-links to hero 
- Font fixes in footer
> Changes to sidebar and Hero Support Component

- minerva-frontend/src/app/components/footer/Footer.jsx
- minerva-frontend/src/app/components/sidebar/Sidebar.jsx
- minerva-frontend/src/app/contact/page.js
Fixed some bugs in /contact
and also Brochures part in Sidebar
also Fixed font sizing in Footer
> Fixed Bugs
